//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTimer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class saved : global::System.Configuration.ApplicationSettingsBase {
        
        private static saved defaultInstance = ((saved)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new saved())));
        
        public static saved Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime GoalEndTime {
            get {
                return ((global::System.DateTime)(this["GoalEndTime"]));
            }
            set {
                this["GoalEndTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoalMessage {
            get {
                return ((string)(this["GoalMessage"]));
            }
            set {
                this["GoalMessage"] = value;
            }
        }
    }
}
